version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main
    versioning-strategy: increase
