name: CI

on: [push]

jobs:
  LintandTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Check StandardRB
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: amoeba/standardrb-action@v2
    - name: Run tests
      run: bundle exec rake test
