name: CI

on: [push]

jobs:
  LintandTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Check StandardRB
      run: bundle exec standardrb

    - name: Run tests
      run: bundle exec rake test
